language: cpp

# speed up incremental builds
cache: ccache

compiler:
  - gcc
  - clang

# preinstalled packages
addons:
  apt:
    packages:
    - bison
    - python3-docutils

# in-tree and out-of-tree builds
# with or without debug
env:
  - BUILD_DIR=.      CONFIG_DIR=.
  - BUILD_DIR=.build CONFIG_DIR=.. CONFIG_FLAGS="--enable-debug"
  - BUILD_DIR=.      CONFIG_DIR=.  CONFIG_FLAGS="--enable-debug" COMMON_FLAGS=-fsanitize=address
  - BUILD_DIR=.      CONFIG_DIR=.  CONFIG_FLAGS="--enable-debug" COMMON_FLAGS=-fsanitize=undefined

script:
  - BASE_FLAGS="-O2 -g"
  - ./autogen.sh
  - mkdir -p $BUILD_DIR && cd $BUILD_DIR
  - |
    $CONFIG_DIR/configure \
        --prefix="$(pwd)"/re2c-install \
        --enable-docs \
        --enable-libs \
        ${CONFIG_FLAGS} \
        CFLAGS="${BASE_FLAGS} ${COMMON_FLAGS}" \
        CXXFLAGS="${BASE_FLAGS} ${COMMON_FLAGS}" \
        LDFLAGS="${BASE_FLAGS} ${COMMON_FLAGS}" || \
    cat config.log
  - make -j$(nproc)
  - make -j$(nproc) check VERBOSE=1
  - make -j$(nproc) install
