language: cpp

compiler:
 - gcc
 - clang

# preinstalled packages
addons:
  apt:
    packages:
    - bison
    - python3-docutils

# in-tree and out-of-tree builds
env:
 - BUILD_DIR=.      CONFIG_DIR=.
 - BUILD_DIR=.build CONFIG_DIR=..

script:
  - ./autogen.sh
  - mkdir -p $BUILD_DIR && cd $BUILD_DIR
  - |
    $CONFIG_DIR/configure \
        --prefix="$(pwd)"/re2c-install \
        --enable-docs \
        --enable-debug \
        --enable-libs
  - make -j$(nproc)
  - make -j$(nproc) check VERBOSE=1
  - make -j$(nproc) install
