language: cpp

# speed up incremental builds
cache: ccache

compiler:
  - gcc
  - clang

# preinstalled packages
addons:
  apt:
    packages:
    - bison
    - python3-docutils

# configurations: cmake/autotools, in-tree/out-of-tree, release/debug, etc.
env:
  - CMAKE=no  BUILD_DIR=.      CONFIG_DIR=.
  - CMAKE=no  BUILD_DIR=.build CONFIG_DIR=.. CONFIG_FLAGS="--enable-debug"
  - CMAKE=yes BUILD_DIR=.      CONFIG_DIR=.  BUILD_TYPE=RelWithDebInfo
  - CMAKE=yes BUILD_DIR=.build CONFIG_DIR=.. BUILD_TYPE=Release
  - CMAKE=yes BUILD_DIR=.build CONFIG_DIR=.. BUILD_TYPE=RelWithDebInfo COMMON_FLAGS=-fsanitize=address
  - CMAKE=yes BUILD_DIR=.build CONFIG_DIR=.. BUILD_TYPE=RelWithDebInfo COMMON_FLAGS=-fsanitize=undefined

script:
  - |
    if [ x${CMAKE} = "xyes" ]; then
      mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR} \
      && cmake \
          -B . -S ${CONFIG_DIR} \
          -DCMAKE_INSTALL_PREFIX="${CONFIG_DIR}/${BUILD_DIR}/install" \
          -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
          -DCMAKE_C_FLAGS="${COMMON_FLAGS}" \
          -DCMAKE_CXX_FLAGS="${COMMON_FLAGS}" \
          -DCMAKE_EXE_LINKER_FLAGS="${COMMON_FLAGS}" \
          -DCMAKE_SHARED_LINKER_FLAGS="${COMMON_FLAGS}" \
          -DRE2C_BUILD_LIBS=on \
          -DRE2C_REBUILD_DOCS=on \
        && make -j$(nproc) \
        && make -j$(nproc) check VERBOSE=1 \
        && make -j$(nproc) install
    else
      BASE_FLAGS="-O2 -g" \
        && ./autogen.sh \
        && mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR} \
            && ${CONFIG_DIR}/configure \
          --prefix="$(pwd)"/re2c-install \
          --enable-docs \
          --enable-libs \
          ${CONFIG_FLAGS} \
          CFLAGS="${BASE_FLAGS} ${COMMON_FLAGS}" \
          CXXFLAGS="${BASE_FLAGS} ${COMMON_FLAGS}" \
          LDFLAGS="${BASE_FLAGS} ${COMMON_FLAGS}" \
        || cat config.log \
        && make -j$(nproc) \
        && make -j$(nproc) check VERBOSE=1 \
        && make -j$(nproc) install
    fi
